#pragma once
#include "nt_include.h"

#define FACILITY_MY 0xFFF


/*0x00  execption*/
#define STATUS_EXECPTION_PROBEREAD (NTSTATUS)0xEFFF0001;
#define STATUS_EXECPTION_PROBEWRITE (NTSTATUS)0xEFFF0002;
#define STATUS_EXECPTION_PROBEREADWRITE (NTSTATUS)0xEFFF0003;

/*0x01  memory*/
#define STATUS_MEMORY_ALLOCATE_UNSUCCESS (NTSTATUS)0xEFFF0101;

/*0x02  thread*/
#define STATUS_THREAD_NOT_FOUND (NTSTATUS)0xEFFF0201;

/*0x03  apc*/
#define STATUS_APC_INSERT_FAILED (NTSTATUS)0xEFFF0301;
